#Prime checker.
def isPrime(num):
    """ (int) -> bool

    Return True if num is a prime and False otherwise.

    >>> isPrime(10)
    False
    >>> isPrime(228)
    False
    >>> isPrime(37)
    True
    """

    test = True
    result = []
    j = 2

    while (j < num and test == True):
        if num % j == 0:
            test = False
        else:
            j = j + 1

    if num <= 1:
        test = False
        
    return test

def LPop(num):
    """ (int) -> list of int

    Return a list of numbers which are numbers generated by continuously
    popping from the left of num.
    
    >>> LPop(46821)
    [46821, 6821, 821, 21, 1]
    >>> LPop(602)
    [602, 2]
    """

    s_num = str(num)
    new_num_str = ''
    temp_list = []
    result_list = []
    
    for i in s_num:
        temp_list.append(i)

#    temp_length = len(temp_list)

# Remove numbers containing 0s.

##    new_list = list(temp_list)
##
##    for i in temp_list:
##
##        checker = True
##        num = i
##        s_num = str(i)
##
##        for j in range(len(s_num)):
##            digit = (num // 10**j) % 10
##            if digit == 0:
##                checker = False
##
##        if checker == False:
##            new_list.remove(num)
##
##    temp_list = new_list

#####
            
    while temp_list != []:        
        for j in range(len(temp_list)):
            new_num_str = new_num_str + temp_list[j]

        new_num = int(new_num_str)

        if new_num not in result_list:
            result_list.append(new_num)
        temp_list.pop(0)
        new_num_str = ''

    return result_list

def RPop(num):
    """ (int) -> list of int

    Return a list of numbers which are numbers generated by continuously
    popping from the right of num.
    
    >>> RPop(46821)
    [46821, 4682, 468, 46, 4]
    >>> RPop(602)
    [602, 60, 6]
    """

    s_num = str(num)
    new_num_str = ''
    temp_list = []
    result_list = []
    
    for i in s_num:
        temp_list.append(i)

    temp_length = len(temp_list)

# Remove numbers containing 0s.

##    new_list = list(temp_list)
##
##    for i in temp_list:
##
##        checker = True
##        num = i
##        s_num = str(i)
##
##        for j in range(len(s_num)):
##            digit = (num // 10**j) % 10
##            if digit == 0:
##                checker = False
##
##        if checker == False:
##            new_list.remove(num)
##
##    temp_list = new_list

#####
            
    while temp_list != []:        
        for j in range(len(temp_list)):
            new_num_str = new_num_str + temp_list[j]

        new_num = int(new_num_str)

        if new_num not in result_list:
            result_list.append(new_num)
        temp_list.pop(-1)
        new_num_str = ''

    return result_list

result_list = []
num = 11
checker = True
i = 0
j = 0

while len(result_list) < 11:

    checker = True
    
    while checker == True and i < len(LPop(num)) and j < len(RPop(num)):        
        if isPrime(LPop(num)[i]) == False:
            checker = False
        if isPrime(RPop(num)[j]) == False:
            checker = False

        i = i + 1
        j = j + 1
        
    if checker == True and num not in result_list:
        result_list.append(num)

    i = 0
    j = 0
    
    num = num + 1

    # Progress monitor

    if num == 10:
        print(num)

    if num == 50:
        print(num)

    if num == 100:
        print(num)

    if num == 500:
        print(num)

    if num == 1000:
        print(num)

    if num == 5000:
        print(num)
        print(result_list)
        

    if num == 10000:
        print(num)

    if num == 50000:
        print(num)

    if num == 100000:
        print(num)

    if num == 500000:
        print(num)

    if num == 1000000:
        print(num)
        
    if len(result_list)/11 in [0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3, 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4, 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5, 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6, 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7, 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8, 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9, 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1]:
        print(str((len(result_list)/11)*100) + '%')


print(result_list)


    
